#! /bin/sh

picom &
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd >/dev/null || sxhkd &

#################################################### SCREEN
bspc monitor eDP1 -s HDMI1
NSCREEN=$(xrandr | grep " connected " | wc -l)

if [[ $NSCREEN -eq 1 ]]; then
  $HOME/.screenlayout/SingleLayout.sh
  bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
fi

if [[ $NSCREEN -eq 2 ]]; then
  $HOME/.screenlayout/MonitorLayout.sh
  bspc monitor eDP1 -d 4 5 6 7 8 9 10
  bspc monitor HDMI1 -d 1 2 3
fi
#################################################### NEERCS

target -r

bspc config border_radius 10
bspc config border_width 1
bspc config focused_border_color \#170606
bspc config normal_border_color \#000000
bspc config window_gap 4
bspc config focus_follows_pointer true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config bottom_padding 0
bspc config upper_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Blueberry.py state=floating rectangle= size center=true <window >+0+0

#################################################### KEYBINDINGS

setxkbmap es

xmodmap -e "clear Lock"
xmodmap -e "keycode 66 = Escape"
xmodmap -e "keycode 135 = Right Caps_Lock NoSymbol NoSymbol NoSymbol NoSymbol"
xmodmap -e "keycode 49 = Mode_switch ordfeminine ordmasculine ordfeminine backslash backslash backslash"
xmodmap -e "keycode 43 = h H Left H"
xmodmap -e "keycode 44 = j J Down J"
xmodmap -e "keycode 45 = k K Up K"
xmodmap -e "keycode 46 = l L Right L"
xmodmap -e "keycode 51 = Return Ccedilla ccedilla Ccedilla braceright dead_breve braceright dead_breve ccedilla Ccedilla braceright dead_breve"

#################################################### SGNIDNIBYEK
easyeffects --gapplication-service &
nitrogen --restore &
xautolock -time 5 -locker /usr/local/bin/auto_lock_screen.sh &
xbanish &
blueberry-tray &
nm-applet --no-agent &
